#!/usr/bin/env bash
# Engram pre-compact hook — runs BEFORE context window compression.
#
# Behavior (autonomous):
#  - APPROVE if a fresh handoff (reason="compact", written within
#    ENGRAM_PRECOMPACT_WINDOW_SEC seconds — default 300) already exists.
#  - Otherwise, auto-generate a mechanical handoff from the transcript
#    (last user messages, edited files, tool calls, commits) and APPROVE.
#
# Why autonomous: the old block-then-approve loop made /compact a two-step
# ritual — the hook would block, the user would have to wait for Claude to
# run five save tools, then re-run /compact. Now /compact "just works":
# the hook writes the lifeline itself, approves, and compaction proceeds.
#
# Claude's MCP instructions still push proactive saves during the session
# (that's where the LLM-distilled facts come from). The hook's job is
# strictly the compact-time lifeline, not session-long memory hygiene.

DATA_DIR="${ENGRAM_DATA_DIR:-${SMART_MEMORY_DATA_DIR:-$HOME/.claude/engram}}"
WINDOW_SEC="${ENGRAM_PRECOMPACT_WINDOW_SEC:-300}"

# Claude Code passes { session_id, transcript_path, trigger, ... } on stdin.
# Capture it so we can parse the transcript for auto-extraction.
PAYLOAD=$(cat 2>/dev/null || true)

RESULT=$(ENGRAM_DATA_DIR="$DATA_DIR" \
         ENGRAM_HANDOFF_DIR="$DATA_DIR/handoffs" \
         WINDOW_SEC="$WINDOW_SEC" \
         CC_PAYLOAD="$PAYLOAD" \
         node -e "
  (() => {
    const fs = require('fs');
    const path = require('path');

    const handoffDir = process.env.ENGRAM_HANDOFF_DIR;
    const windowMs = Number(process.env.WINDOW_SEC) * 1000;

    // Phase 1 — if a fresh compact-reason handoff already exists (Claude
    // wrote one proactively during the session), reuse it and approve.
    try {
      if (fs.existsSync(handoffDir)) {
        const files = fs.readdirSync(handoffDir)
          .filter(f => f.endsWith('.json'))
          .sort()
          .reverse();
        if (files.length) {
          const latest = JSON.parse(fs.readFileSync(path.join(handoffDir, files[0]), 'utf8'));
          const age = Date.now() - new Date(latest.timestamp).getTime();
          if (latest.reason === 'compact' && isFinite(age) && age >= 0 && age <= windowMs) {
            return console.log(JSON.stringify({
              decision: 'approve',
              reason: 'Fresh compact-reason handoff detected — proceeding with compaction.',
            }));
          }
        }
      }
    } catch { /* fall through to auto-generate */ }

    // Phase 2 — auto-generate a mechanical handoff from the transcript.
    let payload = {};
    try { payload = JSON.parse(process.env.CC_PAYLOAD || '{}'); } catch {}
    const transcriptPath = payload.transcript_path;
    const sessionId = payload.session_id || null;

    const handoff = {
      timestamp: new Date().toISOString(),
      sessionId,
      reason: 'compact',
      currentTask: '',
      completed: [],
      nextSteps: [],
      openQuestions: [],
      fileRefs: [],
      decisions: [],
      notes: 'Auto-generated by engram_precompact_hook.sh. ' +
             'Mechanical extraction from transcript — not LLM-distilled. ' +
             'Use memory_handoff_read to resume; call memory_search for richer context.',
    };

    if (transcriptPath && fs.existsSync(transcriptPath)) {
      try {
        const lines = fs.readFileSync(transcriptPath, 'utf8').trim().split('\n');
        const userMsgs = [];
        const fileSet = new Set();
        const writeSet = new Set();
        const commits = [];
        let lastAssistantText = '';

        for (const l of lines) {
          let obj;
          try { obj = JSON.parse(l); } catch { continue; }
          if (obj.type === 'user') {
            const c = obj.message && obj.message.content;
            // Skip tool_result turns — only real user prompts.
            if (Array.isArray(c) && c.some(p => p && p.type === 'tool_result')) continue;
            const text = typeof c === 'string'
              ? c
              : Array.isArray(c)
                ? c.filter(p => p && p.type === 'text').map(p => p.text).join('\n')
                : '';
            if (text.trim()) userMsgs.push(text.trim());
          } else if (obj.type === 'assistant') {
            const c = obj.message && obj.message.content;
            if (!Array.isArray(c)) continue;
            for (const p of c) {
              if (p && p.type === 'text' && p.text) lastAssistantText = p.text;
              if (p && p.type === 'tool_use') {
                const name = p.name || '';
                const input = p.input || {};
                if (name === 'Read' && input.file_path) fileSet.add(input.file_path);
                else if ((name === 'Edit' || name === 'Write' || name === 'NotebookEdit') && input.file_path) {
                  fileSet.add(input.file_path);
                  writeSet.add(input.file_path);
                } else if (name === 'Bash' && typeof input.command === 'string') {
                  const cmd = input.command;
                  const m = cmd.match(/git\s+commit[^\"]*-m\s+[\"']([^\"']+)[\"']/);
                  if (m) commits.push(m[1].split(/\\n|\n/)[0].slice(0, 120));
                }
              }
            }
          }
        }

        if (userMsgs.length) {
          handoff.currentTask = userMsgs[userMsgs.length - 1].split('\n')[0].slice(0, 200);
        }
        // Recent write targets are strong 'completed' signals.
        handoff.completed = [...writeSet].slice(-20).map(f => 'edited ' + f);
        if (commits.length) handoff.decisions = commits.slice(-10).map(m => 'commit: ' + m);
        handoff.fileRefs = [...fileSet].slice(-30);
        if (lastAssistantText) {
          const tail = lastAssistantText.trim().split('\n').slice(-3).join(' ').slice(0, 300);
          if (tail) handoff.notes += '\n\nLast assistant note: ' + tail;
        }
      } catch (e) {
        handoff.notes += '\n\nTranscript parse failed: ' + (e && e.message ? e.message : String(e));
      }
    } else {
      handoff.notes += '\n\nNo transcript_path on stdin — minimal handoff only.';
    }

    // Write the handoff (JSON + markdown) so memory_handoff_read can pick it up.
    try {
      if (!fs.existsSync(handoffDir)) fs.mkdirSync(handoffDir, { recursive: true });
      const stamp = new Date().toISOString().replace(/[:.]/g, '-').replace('T', '_').split('-').slice(0, 6).join('-');
      fs.writeFileSync(path.join(handoffDir, stamp + '.json'), JSON.stringify(handoff, null, 2), 'utf8');
      const md = [
        '# Handoff — ' + handoff.timestamp,
        '',
        '**Reason:** ' + handoff.reason + '  (auto-generated)',
        handoff.sessionId ? '**Session:** ' + handoff.sessionId : '',
        '',
        '## Current Task',
        handoff.currentTask || '_unspecified_',
        '',
      ];
      if (handoff.completed.length) md.push('## Completed', ...handoff.completed.map(c => '- ' + c), '');
      if (handoff.fileRefs.length) md.push('## File Refs', ...handoff.fileRefs.map(f => '- ' + f), '');
      if (handoff.decisions.length) md.push('## Decisions', ...handoff.decisions.map(d => '- ' + d), '');
      if (handoff.notes.trim()) md.push('## Notes', handoff.notes.trim(), '');
      fs.writeFileSync(
        path.join(handoffDir, stamp + '.md'),
        md.filter((l, i, a) => !(l === '' && a[i - 1] === '')).join('\n'),
        'utf8',
      );
    } catch (e) {
      // If we can't write the handoff file, still approve — blocking /compact
      // on a filesystem error would strand the user.
      return console.log(JSON.stringify({
        decision: 'approve',
        reason: 'Handoff auto-write failed (' + (e && e.message ? e.message : 'unknown') + '); approving compaction anyway.',
      }));
    }

    console.log(JSON.stringify({
      decision: 'approve',
      reason: 'Auto-generated compact handoff from transcript — proceeding with compaction.',
    }));
  })();
" 2>/dev/null)

if [ -z "$RESULT" ]; then
  # Last-resort failsafe: if the node extractor itself crashes, don't
  # strand the user — approve so /compact can proceed.
  echo '{"decision":"approve","reason":"engram_precompact_hook extractor failed; approving compaction to avoid blocking."}'
  exit 0
fi

echo "$RESULT"
