// ── Memory Tiers ─────────────────────────────────────────────────────
// daily -> short-term -> long-term -> archive
// Each tier has different retention and decay characteristics.

export type MemoryTier = 'scratch' | 'daily' | 'short-term' | 'long-term' | 'archive';
export type MemoryType = 'fact' | 'preference' | 'decision' | 'context' | 'correction';
export type CognitiveLayer = 'episodic' | 'semantic' | 'procedural';
export type Sentiment = 'frustrated' | 'curious' | 'satisfied' | 'neutral' | 'excited' | 'confused';

// User-asserted memories (origin='user') are user-territory: protected from
// auto-merge, content rewrites, and demotion-to-archive. Derived memories
// (extracted from conversation, imported, or generated by consolidation)
// stay subject to the full lifecycle.
export type MemoryOrigin = 'user' | 'derived' | 'extracted' | 'imported';

// ── Memory Chunk ─────────────────────────────────────────────────────

export interface MemoryChunk {
  id: string;
  tier: MemoryTier;
  content: string;
  type: MemoryType;
  cognitiveLayer: CognitiveLayer;
  tags: string[];
  domain: string;  // project or domain namespace (e.g. "finch-core", "work")
  topic: string;   // topic within the domain (e.g. "auth", "deployment")
  source: string;  // conversation or session ID
  importance: number; // 0.0-1.0
  sentiment: Sentiment;
  createdAt: string;
  lastRecalledAt: string | null;
  recallCount: number;
  embedding?: number[];
  // FSRS fields (Improvement 3)
  stability?: number;          // S in FSRS -- memory strength in days (default 1.0)
  difficulty?: number;         // D in FSRS -- 0.0-1.0, retention difficulty (default 0.3)
  // Temporal anchor (Improvement 2)
  temporalAnchor?: number;     // Epoch ms of detected date in content
  // Episodic consolidation (Improvement 8)
  consolidationLevel?: number; // 0=raw, 1=episode summary, 2=principle
  sourceChunkIds?: string[];   // For L1/L2, the chunks this was derived from
  // Embedding version tracking (Improvement 6)
  embeddingVersion?: number;   // 1=MiniLM-384, 2=nomic-256
  // Sub-session chunking
  parentChunkId?: string;      // For sub-chunks, the parent chunk ID
  // Provenance — controls whether consolidation may rewrite/forget this chunk
  origin?: MemoryOrigin;       // Default 'derived' for backward compat
}

// ── Memory Edges (Graph) ─────────────────────────────────────────────

export interface MemoryEdge {
  targetId: string;
  relationship: 'temporal' | 'semantic' | 'causal' | 'co-recalled';
  weight: number; // 0.0-1.0
  createdAt: string;
}

// ── Recall Outcomes ──────────────────────────────────────────────────

export interface RecallOutcome {
  conversationId: string;
  outcome: 'helpful' | 'corrected' | 'irrelevant';
  timestamp: string;
}

// ── Procedural Rules ─────────────────────────────────────────────────

export interface ProceduralRule {
  id: string;
  rule: string;
  domain: 'code' | 'communication' | 'workflow' | 'preference' | 'general';
  /** Empty means everywhere; otherwise the project slug the rule belongs to. */
  scope?: string;
  confidence: number; // 0.0-1.0
  reinforcements: number;
  contradictions: number;
  evidence: string[];
  createdAt: string;
  updatedAt: string;
}

// ── Knowledge Graph ─────────────────────────────────────────────────

export interface KnowledgeTriple {
  id: string;
  subject: string;
  predicate: string;
  object: string;
  source: string;
  confidence: number; // 0.0-1.0
  validFrom: string;
  validTo: string | null; // null = still valid
  createdAt: string;
}

// ── Diary ───────────────────────────────────────────────────────────

export interface DiaryEntry {
  date: string;
  time: string;
  content: string;
  agent: string;
}

// ── Daily Logs ───────────────────────────────────────────────────────

export interface DailyLogEntry {
  timestamp: string;
  conversationId: string;
  summary: string;
  extractedFacts: string[];
}

// ── Search Results ───────────────────────────────────────────────────

export interface SearchResult {
  chunk: MemoryChunk;
  /** Composite ranking score. Under RRF (the default) this is a rank-fusion
   *  value in the ~0.003-0.07 band — it orders results but is NOT a 0..1
   *  relevance. Use vectorSimilarity for absolute thresholds. */
  score: number;
  /** Raw vector-stage cosine similarity (0..1), present when the chunk
   *  passed the vector stage. Absent for keyword-only / graph-walk hits. */
  vectorSimilarity?: number;
}

// ── Config ───────────────────────────────────────────────────────────

export interface SmartMemoryConfig {
  /** Root data directory (default: ~/.claude/engram) */
  dataDir: string;
  /** Days before daily tier moves to short-term (default: 2) */
  dailyRetentionDays: number;
  /** Days before short-term promotes to long-term if recalled (default: 14) */
  shortTermRetentionDays: number;
  /** Days before long-term demotes to archive if stale (default: 90) */
  longTermRetentionDays: number;
  /** Max chunks to return per search (default: 10) */
  maxRecallChunks: number;
  /** Max tokens budget for recalled memories (default: 1500) */
  maxRecallTokens: number;
  /** Minimum messages before triggering extraction (default: 3) */
  extractionThreshold: number;
  /** Mem0 API key (optional -- enables Mem0 cloud extraction) */
  mem0ApiKey: string;
  /** Mem0 user ID for scoping memories (default: 'default') */
  mem0UserId: string;
  /** Extraction provider: 'local' or 'mem0' or 'both' (default: 'local') */
  extractionProvider: 'local' | 'mem0' | 'both';
  // v2 feature flags
  /** Use Reciprocal Rank Fusion for hybrid search merging (default: true) */
  enableRRF: boolean;
  /** Use FSRS spaced repetition for importance decay (default: true) */
  enableFSRS: boolean;
  /** Prepend contextual prefix to chunks before embedding (default: true) */
  enableContextualPrefix: boolean;
  /** Prioritize consolidation by importance * recency * surprise (default: true) */
  enableBiasedReplay: boolean;
  /** Use cross-encoder model for reranking (default: false, requires model download) */
  enableCrossEncoderRerank: boolean;
  /** Cluster episodic memories into semantic summaries (default: true) */
  enableEpisodicConsolidation: boolean;
  /** Embedding dimensions for Matryoshka truncation (default: 384 for backward compat) */
  embeddingDimensions: number;
  /** Split long content into focused sub-chunks at ingest time (default: true) */
  enableChunking: boolean;
  /** Persist diagnostic retrieval traces under <dataDir>/traces (default: false).
   *  When enabled, every search() call writes a JSON trace capturing the query,
   *  per-stage candidate counts, final result IDs, and total latency. */
  enableRetrievalTraces: boolean;
  /** Days to keep retrieval traces before garbage collection (default: 7). */
  retrievalTraceRetentionDays: number;
}

export const DEFAULT_CONFIG: SmartMemoryConfig = {
  dataDir: '',
  dailyRetentionDays: 2,
  shortTermRetentionDays: 14,
  longTermRetentionDays: 90,
  maxRecallChunks: 10,
  maxRecallTokens: 50000,
  extractionThreshold: 3,
  mem0ApiKey: '',
  mem0UserId: 'default',
  extractionProvider: 'local',
  enableRRF: true,
  enableFSRS: true,
  enableContextualPrefix: true,
  enableBiasedReplay: true,
  enableCrossEncoderRerank: false,
  enableEpisodicConsolidation: true,
  embeddingDimensions: 384,
  enableChunking: true,
  enableRetrievalTraces: false,
  retrievalTraceRetentionDays: 7,
};
